name: Deploy static content to Pages

on:
  push:
    branches: ["main"]  # Trigger deployment saat ada push ke branch 'main'
  workflow_dispatch:  # Dapat juga dijalankan manual dari tab Actions

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Checkout kode dari repo

      - name: Setup Pages
        uses: actions/configure-pages@v5  # Persiapkan environment untuk GitHub Pages

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'ikhsanudin/index.html'  # Upload seluruh file dari root repository, pastikan index.html ada di sini

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
